### ISSUE TITLE
pymongo.errors.OperationFailure

### ISSUE THREAD

**Issue by Saibo-creator** [derlin/swisstext-lrec#3]
Hello, I'm trying to reproduce your corpus scraping as described in the paper (LREC, 2019): Automatic Creation of Text Corpora for Low-Resource Languages from the Internet: The Case of Swiss German. I ran into such error :
`pymongo.errors.OperationFailure: Caught exception during index builder initialization st-mongo.urls (903b8268-95c4-429c-af2d-29bd119aae99): 1 provided. First index spec: { ns: "st-mongo.urls", v: 2, key: { url: "hashed", source.extra: 1 }, background: false, name: "url_hashed_source.extra_1" }`

### To reproduce:

- Do installation steps following the readme of repo https://github.com/derlin/swisstext-lrec#installation

- Create a txt file under `swisstext-lrec/` named “swiss-german-sentences.txt” and paste the following text into it. `vim swiss-german-sentences.txt`
`Bettwanze und Vire im Gepäck Vorsorg Wer jetzt sini Sommerferie buecht, sött a möglichi unerwünschti Gescht dänke:
Epidemie, Wire und Wanze sind im Vormarsch.
Villi buechet jetzt Griechäland wäge de günschtige Agebot.
Doch Achtung:
Uf de Website Savetravel.ch warnt es Expertekomitee vor ere neue Tollwuet-epidemie.
Tollwuet wird dur de Speichel vo infizierte Säugetier( Hünd, Chatze, Nagetier und Flädermüüs) wiitergäh.
Tollwuet isch, wänn nüd rächtzytig behandlet, tödlich.
Drum impfe lah.
Wer liäber Richtig Asie flügt, söt abkläre, wie s ums neue« Chikungunya Fiäber» staaht.
Das wird vor allem us Indonesie, Bali, Java, Sumatra und Singapur gmäldet.
In Ostjakarta sind rund 200 Fäll regischtriert wordä.
än Impfschtoff gits no keine.
Typischi Symptom sind Glänkschmerzä i de Chnü und Chnöchel.
Dezue chömet typischi Grippe-symptom wie Temperatur, Kopfweh und Bindehutentzündig.
Fans vo Kuba söttet sich vor de Cholera in Acht neeh.
Suscht tanzt d Krankheit plöztli Samba im Organismus.
Es Souvenir, wo me guet chönnt verzichte.
Ufpasse sött me au im arabischä Ruum.`

- python src/seeding/random_generator.py -i swiss-german-sentences.txt -o seeds.txt
- You can **either** use the bert model as mentioned in the documentation **or** use my fasttext based language identification model, in case you use my fasttext based model:
- `vim swisstext-lrec/src/seeding/generator_base.py `

- add `import fasttext as ft` at the top of the script

- replace line 28 self.lid = BertLid() by
```
        lid_path_format = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'langdetect_filt2-4-150k.ftz')

        self.lid = ft.load_model(lid_path_format)
```
- `vim swisstext-lrec/src/seeding/random_generator.py `

- replace line 28 `proba = self.lid.predict([seed])[0]` by `proba = self.lid.predict([seed])[1][0].item()`

-Download model from https://drive.google.com/file/d/1WUFwx8GZDopPOLKhIj9r7OmQS9o1_UsV/view?usp=sharing into `swisstext-lrec/src/seeding/`

- Install docker: sudo apt install docker.io

- get the latest mongodb image
`docker pull mongo:latest`

- create a directory for persisting the database
`mkdir mongodir`

- launch a mongodb container called st-mongo
`docker run -d --name st-mongo -p 27017:27017 -v $(pwd)/mongodir:/data/db mongo`

- generate some seeds, e.g. `python src/seeding/random_generator.py -i swiss-german-sentences.txt -o seeds.txt`

- run the searcher, e.g. `st_search -c config/prod_config.yaml from_file seeds.txt`

then I got error 

```
$st_search -c config/prod_config.yaml from_file seeds.txt
2020-07-07T13:16:57 [swisstext.searching INFO ] Using config:
crawler_options:
  keep_bad: false
normalizer_options:
  fix_encoding: true
  strip_emojis: true
options:
  crawl_depth: 3
  max_fetches: -1
  max_results: 20
  min_proba: 0.92
  num_workers: 3
pipeline:
  crawler: .JustextCrawler
  decider: lrec_tools.Decider
  normalizer: .Normalizer
  sg_detector: .SwigspotLangid
  splitter: .MocySplitter
  url_filter: lrec_tools.SgUrlFilter
saver_options:
  db: swisstext
  host: localhost
  port: 27017
search_engine:
  _base_package: swisstext.cmd.searching.tools
  query_builder: .QuoteWordsQueryBuilder
  saver: .MongoSaver
  searcher: .StartPageGeneratorFactory
sg_detector_options:
  chunk_size: 1000
splitter_options:
  keep_newlines: true
  more: true

2020-07-07T13:16:57 [swisstext.searching INFO ] About to search 10 seeds
2020-07-07T13:16:57 [swisstext.cmd.searching.pipeline INFO ] Searching seed='typischi vo de', query='"typischi" "vo" "de"'
Traceback (most recent call last):
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/bin/st_search", line 11, in <module>
    load_entry_point('swisstext-cmd==0.0.1', 'console_scripts', 'st_search')()
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/cmd/searching/__main__.py", line 3, in main
    cli()
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/cmd/searching/commandline.py", line 161, in from_file
    _search(ctx, seeds)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/cmd/searching/commandline.py", line 171, in _search
    new_urls_found = ctx.search_engine.process(tasks, max_results=ctx.config.options.max_results)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/cmd/searching/pipeline.py", line 38, in process
    new_count += self.process_one(seed, **kwargs)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/cmd/searching/pipeline.py", line 58, in process_one
    link, ok = self.check_link(raw_link)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/cmd/searching/pipeline.py", line 102, in check_link
    status = self.saver.link_exists(link)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/cmd/searching/tools/mongo_saver.py", line 42, in link_exists
    return ISaver.LinkStatus(MongoURL.exists(url))
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/mongo/abstract/urls.py", line 86, in exists
    return cls.get(url, id) is not None
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/mongo/abstract/urls.py", line 102, in get
    return cls.objects(url=url).first()
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/mongoengine/document.py", line 208, in _get_collection
    cls.ensure_indexes()
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/mongoengine/document.py", line 888, in ensure_indexes
    collection.create_index(fields, background=background, **opts)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/pymongo/collection.py", line 1995, in create_index
    self.__create_index(keys, kwargs, session, **cmd_options)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/pymongo/collection.py", line 1894, in __create_index
    session=session)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/pymongo/collection.py", line 250, in _command
    user_fields=user_fields)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/pymongo/pool.py", line 613, in command
    user_fields=user_fields)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/pymongo/network.py", line 167, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/pymongo/helpers.py", line 159, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Caught exception during index builder initialization swisstext.urls (7ea596a0-fb48-4aa2-a96c-6b762c4b0744): 1 provided. First index spec: { ns: "swisstext.urls", v: 2, key: { url: "hashed", source.extra: 1 }, background: false, name: "url_hashed_source.extra_1" }
```

environment info:
Name: pymongo
Version: 3.10.1

Name: mongoengine
Version: 0.18.2

Name: flask-mongoengine
Version: 0.9.5

Name:MongoDB
Version: 4.2.8

**Comment by derlin** [comment]
in `swisstext/src/mongo/swisstext/mongo/abstract/urls.py`, can you replace the meta definition on line 73 with the snippet below and tell me if this works ?

```python
    meta = {'collection': 'urls', 'abstract': True, 'indexes': [
        {'fields': ['#url']}, # add a hashed index on URL 
        {'fields': ['source.extra']}  # one for speeding up seeds view in frontend
    ]}
```

(NOTE: in your case, the source files would be in your `venv/lib/pythonXX/site-packages/swisstext`)

**Comment by Saibo-creator** [comment]
I did so, it gave another error as follows
```

$st_search -c config/prod_config.yaml from_file seeds.txt                                      
2020-07-07T14:17:56 [swisstext.searching INFO ] Using config:
crawler_options:
  keep_bad: false
normalizer_options:
  fix_encoding: true
  strip_emojis: true
options:
  crawl_depth: 3
  max_fetches: -1
  max_results: 20
  min_proba: 0.92
  num_workers: 3
pipeline:
  crawler: .JustextCrawler
  decider: lrec_tools.Decider
  normalizer: .Normalizer
  sg_detector: .SwigspotLangid
  splitter: .MocySplitter
  url_filter: lrec_tools.SgUrlFilter
saver_options:
  db: swisstext
  host: localhost
  port: 27017
search_engine:
  _base_package: swisstext.cmd.searching.tools
  query_builder: .QuoteWordsQueryBuilder
  saver: .MongoSaver
  searcher: .StartPageGeneratorFactory
sg_detector_options:
  chunk_size: 1000
splitter_options:
  keep_newlines: true
  more: true

2020-07-07T14:17:56 [swisstext.searching INFO ] About to search 10 seeds
Traceback (most recent call last):
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/cmd/base_config.py", line 194, in instantiate_tools
    ToolClass = getattr(importlib.import_module(module_name), class_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/cmd/searching/tools/__init__.py", line 17, in <module>
    from .mongo_saver import MongoSaver
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/cmd/searching/tools/mongo_saver.py", line 4, in <module>
    from swisstext.mongo.models import MongoSeed, MongoURL, SourceType, Source, MongoBlacklist
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/mongo/models.py", line 67, in <module>
    class MongoSentence(AbstractMongoSentence):
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/mongoengine/base/metaclasses.py", line 364, in __new__
    meta['index_specs'] = new_class._build_index_specs(meta['indexes'])
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/mongoengine/base/document.py", line 756, in _build_index_specs
    index_specs = [cls._build_index_spec(spec) for spec in meta_indexes]
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/mongoengine/base/document.py", line 756, in <listcomp>
    index_specs = [cls._build_index_spec(spec) for spec in meta_indexes]
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/mongoengine/base/document.py", line 846, in _build_index_spec
    fields = cls._lookup_field(parts)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/mongoengine/base/document.py", line 1032, in _lookup_field
    raise LookUpError('Cannot resolve field "%s"' % field_name)
mongoengine.errors.LookUpError: Cannot resolve field "source"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/bin/st_search", line 11, in <module>
    load_entry_point('swisstext-cmd==0.0.1', 'console_scripts', 'st_search')()
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/cmd/searching/__main__.py", line 3, in main
    cli()
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/cmd/searching/commandline.py", line 161, in from_file
    _search(ctx, seeds)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/cmd/searching/commandline.py", line 171, in _search
    new_urls_found = ctx.search_engine.process(tasks, max_results=ctx.config.options.max_results)
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/cmd/searching/commandline.py", line 49, in search_engine
    self._search_engine = self.config.create_search_engine()
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/cmd/searching/config.py", line 66, in create_search_engine
    return SearchEngine(*self.instantiate_tools())
  File "/home/ubuntu/SwissCrawl/swisstext-lrec/venv/lib/python3.6/site-packages/swisstext/cmd/base_config.py", line 199, in instantiate_tools
    (e, module_name, class_name, arguments))
RuntimeError: Error instantiating query_builder (swisstext.cmd.searching.tools.QuoteWordsQueryBuilder({}))
```

**Comment by Saibo-creator** [comment]
The meta definition you mentioned is on line 217 in my case. Is it normal?

**Comment by derlin** [comment]
Oops, sorry, I meant in `urls.py`, not `sentences.py`. This is why it is complaining ^^'.

So, to summarize, in `sentences.py`, back to the original (shown below for reference):
```python
    meta = {'collection': 'sentences', 'abstract': True, 'indexes': [
        {'fields': ['-date_added']},  # add a sorted (descending) index on the date_added
        {'fields': ['#url']} # hashed index on url
    ]}
```
and in `urls.py`, change the meta as per the comment above (that I edited).

**Comment by Saibo-creator** [comment]
It works,:thumbsup:

**Comment by derlin** [comment]
great. I'll close the issue then.
